Traceback (most recent call last):
  File "C:\Git\Virtual-Hand\PythonScripts\SensorListener.py", line 27, in __init__
    self.port = serial.Serial('COM3', 9600, timeout=100)  # for COM3
  File "C:\Users\Michael\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\Michael\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Users\Michael\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM3': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Git\Virtual-Hand\PythonScripts\HandController.py", line 32, in <module>
    sensor_data = SensorReadingsListener()
  File "C:\Git\Virtual-Hand\PythonScripts\SensorListener.py", line 32, in __init__
    if self.port.isOpen():
AttributeError: 'SensorReadingsListener' object has no attribute 'port'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Git\Virtual-Hand\PythonScripts\ClientConnectionHandlerV2.py", line 61, in data_receiver_thread_method
    recv_input = self.input_socket.recv(1024).decode("utf-8")
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
